controllers:
    resource: ../src/Controller/
    type: attribute
    
contact:
    path: /contact
    controller: App\Controller\ContactPageController::index

product_show:
    path: /product/{id}
    controller: App\Controller\ProductController::show

product_edit:
    path: /product/{id}/edit
    controller: App\Controller\ProductController::edit

product_new:
    path: /product/new
    controller: App\Controller\ProductController::new

product_delete:
    path: '/product/{id}'
    controller: 'App\Controller\ProductController::delete'
    methods: ['POST']

quotation_new:
    path: /quotation/new
    controller: App\Controller\QuotationController::new

quotation_index:
    path: /quotation
    controller: App\Controller\QuotationController::index

quotation_delete:
    path: /quotation/delete/{id}
    controller: App\Controller\QuotationController::delete

quotation_edit:
    path: /quotation/edit/{id}
    controller: App\Controller\QuotationController::edit

app_pdf:
    path: /pdf/{id}/{facture}
    controller: App\Controller\PdfController::index

quotation_view:
    path: /quotation/view/{id}
    controller: App\Controller\QuotationController::view

line_create:
    path: '/line/create/{quotation_id}'
    controller: App\Controller\LineController::create

line_delete:
    path: '/line/delete/{quotation_id}/{line_id}'
    controller: 'App\Controller\LineController::delete'
    methods: ['POST']

line_edit:
    path: '/line/edit/{quotation_id}/{line_id}'
    controller: 'App\Controller\LineController::edit'
